### ISSUE TITLE
Bloqueos Transaccionales

### ISSUE THREAD

**Issue by EPERAMAS** [EPERAMAS/pMonitor#3]
Se detecta que pMonitor NO está reportando bloqueos de transacciones cuando los spid que se bloquean pertenecen a un mismo loginame @JavierPNT

**Comment by JorgePeramas** [comment]
En la versión de desarrollo ya se solucionó el problema, está pendiente realizar un merge con el branch master

**Comment by EPERAMAS** [comment]
Se realizaron pruebas y fueron exitosas.
